#Libs
All: libutil libgraphics libdata libllist liblpthread

libutil: 
		(cd util && make)

libgraphics: 
		(cd graphics && make)

libdata:
		(cd data && make)

libllist:
		(cd linkedlist && make)

liblpthread:
		(cd lpthread && make)